server:
  port: 8080

spring:
  profiles:
    active: local

  main:
    allow-bean-definition-overriding: true

  devtools:
    livereload:
      enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: basic

siseme-client:
  ribbon:
    listOfServers: https://sise.me

task:
  execution:
    pool:
      core-size: 8
      max-size: 8
    thread-name-prefix: daum-thread
  output:
    ansi:
      enabled: always