spring:
  jpa:
    database: MYSQL
    showSql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.format_sql: true
      hibernate.use_sql_comments: true

  datasource:
    url: '{cipher}7f72ab9d3ca220ca6f7eb1d158f96649c32cc71ea49450416e8a788d223a75fa714f0bc766d88ed199335618394d1ec3b09af9e9121c511057c33960fdd61dfd60d92eff7b63e46fb689f3f9d91b6a3053231a14cee4c6da3d25dcd93f2d6e629d7017c596450d
                  5246f0bf6211ffb9d86b08840e707c630fa23a6aa5fe091a2941a01ca84d5c83a40463e57b38c3498c'
    username: '{cipher}2584e761373ed601559fa350b99b1b9ffdb0dc79dacb34ed0b1adf589e90a8e3'
    password: '{cipher}12c3f3ba9d9cee38d160e1f88998e731512644867b0ab6af983bff0245c24a42'
    driverClassName: org.mariadb.jdbc.Driver
    initialization-mode: NEVER

    hikari:
      maximum-pool-size: 20
      connection-timeout: 2000
      connection-test-query: SELECT 1
      validation-timeout: 5000
      data-source-properties:
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        useServerPrepStmts: true