# feign
feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: basic
siseme-client:
  ribbon:
    listOfServers: https://sise.me
daum-client:
  ribbon:
    listOfServers: https://dapi.kakao.com
